-- user
insert into Account (roles,email,password) values ('Admin','admin','jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=');
insert into Account (roles,email,password) values ('Member','user','BPiZbadjt6lpsQKO4wB1aerzpjVIbdqyEdUSyFud+Ps=');

-- locations
insert into country (code,name,del_flag) values ('MM','Myanmar',false);
insert into country (code,name,del_flag) values ('JP','Japan',false);

insert into state (name,country_id,del_flag) values ('Ayeyarwady Region',1,false);
insert into state (name,country_id,del_flag) values ('Bago Region',1,false);
insert into state (name,country_id,del_flag) values ('Chin State',1,false);
insert into state (name,country_id,del_flag) values ('Kachin State',1,false);
insert into state (name,country_id,del_flag) values ('Kayah State',1,false);
insert into state (name,country_id,del_flag) values ('Kayin State',1,false);
insert into state (name,country_id,del_flag) values ('Magway Region',1,false);
insert into state (name,country_id,del_flag) values ('Mandalay Region',1,false);
insert into state (name,country_id,del_flag) values ('Mon State',1,false);
insert into state (name,country_id,del_flag) values ('Rakhine State',1,false);
insert into state (name,country_id,del_flag) values ('Shan State',1,false);
insert into state (name,country_id,del_flag) values ('Sagaing Region',1,false);
insert into state (name,country_id,del_flag) values ('Tanintharyi Region',1,false);
insert into state (name,country_id,del_flag) values ('Yangon Region',1,false);
insert into state (name,country_id,del_flag) values ('Naypyidaw Union Territory',1,false);

insert into city (name,state_id,del_flag) values ('Gangaw Township',7,false);
insert into city (name,state_id,del_flag) values ('Saw Township',7,false);
insert into city (name,state_id,del_flag) values ('Tilin Township',7,false);
insert into city (name,state_id,del_flag) values ('Kyaukhtu Subtownship',7,false);
insert into city (name,state_id,del_flag) values ('Chauck Township',7,false);
insert into city (name,state_id,del_flag) values ('Magway Township',7,false);
insert into city (name,state_id,del_flag) values ('Myothit Township',7,false);
insert into city (name,state_id,del_flag) values ('Natmauk Township',7,false);
insert into city (name,state_id,del_flag) values ('Taungdwingyi Township',7,false);
insert into city (name,state_id,del_flag) values ('Yenangyaung Township',7,false);
insert into city (name,state_id,del_flag) values ('Minbu Township',7,false);
insert into city (name,state_id,del_flag) values ('Ngape Township',7,false);
insert into city (name,state_id,del_flag) values ('Pwintbyu Township',7,false);
insert into city (name,state_id,del_flag) values ('Salin Township',7,false);
insert into city (name,state_id,del_flag) values ('Sidoktaya Township',7,false);
insert into city (name,state_id,del_flag) values ('Myaing Township',7,false);
insert into city (name,state_id,del_flag) values ('Pakokku Township',7,false);
insert into city (name,state_id,del_flag) values ('Pauk Township',7,false);
insert into city (name,state_id,del_flag) values ('Seikphyu Township',7,false);
insert into city (name,state_id,del_flag) values ('Yesagyo Township',7,false);
insert into city (name,state_id,del_flag) values ('Aunglan Township',7,false);
insert into city (name,state_id,del_flag) values ('Kamma Township',7,false);
insert into city (name,state_id,del_flag) values ('Mindon Township',7,false);
insert into city (name,state_id,del_flag) values ('Minhla Township',7,false);
insert into city (name,state_id,del_flag) values ('Sinbaungwe Township',7,false);
insert into city (name,state_id,del_flag) values ('Thayet Township',7,false);
insert into city (name,state_id,del_flag) values ('Kyaukse Township',8,false);
insert into city (name,state_id,del_flag) values ('Myittha Township',8,false);
insert into city (name,state_id,del_flag) values ('Sintgaing Township',8,false);
insert into city (name,state_id,del_flag) values ('Tada-U Township',8,false);
insert into city (name,state_id,del_flag) values ('Amarapura Township',8,false);
insert into city (name,state_id,del_flag) values ('Aungmyethazan Township',8,false);
insert into city (name,state_id,del_flag) values ('Chanayethazan Township',8,false);
insert into city (name,state_id,del_flag) values ('Chanmyathazi Township',8,false);
insert into city (name,state_id,del_flag) values ('Mahaaungmye Township',8,false);
insert into city (name,state_id,del_flag) values ('Patheingyi Township',8,false);
insert into city (name,state_id,del_flag) values ('Pyigyidagun Township',8,false);
insert into city (name,state_id,del_flag) values ('Mahlaing Township',8,false);
insert into city (name,state_id,del_flag) values ('Meiktila Township',8,false);
insert into city (name,state_id,del_flag) values ('Thazi Township',8,false);
insert into city (name,state_id,del_flag) values ('Wundwin Township',8,false);
insert into city (name,state_id,del_flag) values ('Myingyan Township',8,false);
insert into city (name,state_id,del_flag) values ('Natogyi Township',8,false);
insert into city (name,state_id,del_flag) values ('Nganzun Township',8,false);
insert into city (name,state_id,del_flag) values ('Thaungtha Township',8,false);
insert into city (name,state_id,del_flag) values ('Nyaung-U Township',8,false);
insert into city (name,state_id,del_flag) values ('Kyaukpadaung Township',8,false);
insert into city (name,state_id,del_flag) values ('Ngathayauk Subtownship',8,false);
insert into city (name,state_id,del_flag) values ('Madaya Township',8,false);
insert into city (name,state_id,del_flag) values ('Mogok Township',8,false);
insert into city (name,state_id,del_flag) values ('Pyinoolwin Township',8,false);
insert into city (name,state_id,del_flag) values ('Singu Township',8,false);
insert into city (name,state_id,del_flag) values ('Thabeikkyin Township',8,false);
insert into city (name,state_id,del_flag) values ('Tagaung Subtownship',8,false);
insert into city (name,state_id,del_flag) values ('Pyawbwe Township',8,false);
insert into city (name,state_id,del_flag) values ('Yamethin Township',8,false);
insert into city (name,state_id,del_flag) values ('Dekkhinathiri Township',15,false);
insert into city (name,state_id,del_flag) values ('Lewe Township',15,false);
insert into city (name,state_id,del_flag) values ('Pyinmana Township',15,false);
insert into city (name,state_id,del_flag) values ('Zabuthiri Township',15,false);
insert into city (name,state_id,del_flag) values ('Ottarathiri Township',15,false);
insert into city (name,state_id,del_flag) values ('Pobbathiri Township',15,false);
insert into city (name,state_id,del_flag) values ('Tatkon Township',15,false);
insert into city (name,state_id,del_flag) values ('Zeyarthiri Township',15,false);
insert into city (name,state_id,del_flag) values ('Bawlakhe Township',5,false);
insert into city (name,state_id,del_flag) values ('Hpasawng Township',5,false);
insert into city (name,state_id,del_flag) values ('Mese Township',5,false);
insert into city (name,state_id,del_flag) values ('Ywathit Subtownship',5,false);
insert into city (name,state_id,del_flag) values ('Demoso Township',5,false);
insert into city (name,state_id,del_flag) values ('Hpruso Township',5,false);
insert into city (name,state_id,del_flag) values ('Loikaw Township',5,false);
insert into city (name,state_id,del_flag) values ('Shadaw Township',5,false);
insert into city (name,state_id,del_flag) values ('Kengtung Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong Khet Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong La Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong Yang Township',11,false);
insert into city (name,state_id,del_flag) values ('Mine Pauk Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Minelar Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Mong Hpayak Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong Yawng Township',11,false);
insert into city (name,state_id,del_flag) values ('Mineyu Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Mong Hsat Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong Ping Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong Tong Township',11,false);
insert into city (name,state_id,del_flag) values ('Minekoke Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Monehta Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Ponparkyin Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Tontar Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Tachileik Township',11,false);
insert into city (name,state_id,del_flag) values ('Kyaing Lap Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Talay Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Kunlong Township',11,false);
insert into city (name,state_id,del_flag) values ('Hsipaw Township',11,false);
insert into city (name,state_id,del_flag) values ('Kyaukme Township',11,false);
insert into city (name,state_id,del_flag) values ('Mantong Township',11,false);
insert into city (name,state_id,del_flag) values ('Namhsan Township',11,false);
insert into city (name,state_id,del_flag) values ('Namtu Township',11,false);
insert into city (name,state_id,del_flag) values ('Nawnghkio Township',11,false);
insert into city (name,state_id,del_flag) values ('Minelon Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Minengaw Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Hsenwi Township',11,false);
insert into city (name,state_id,del_flag) values ('Lashio Township',11,false);
insert into city (name,state_id,del_flag) values ('Mongyai Township',11,false);
insert into city (name,state_id,del_flag) values ('Tangyan Township',11,false);
insert into city (name,state_id,del_flag) values ('Laukkaing Township',11,false);
insert into city (name,state_id,del_flag) values ('Konkyan Township',11,false);
insert into city (name,state_id,del_flag) values ('Chinshwehaw Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Mawhtike Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Kutkai Township',11,false);
insert into city (name,state_id,del_flag) values ('Mu Se Township',11,false);
insert into city (name,state_id,del_flag) values ('Namhkam Township',11,false);
insert into city (name,state_id,del_flag) values ('Manhero Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Monekoe Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Pansai Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Tamoenye Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Hopang Township',11,false);
insert into city (name,state_id,del_flag) values ('Mongmao Township',11,false);
insert into city (name,state_id,del_flag) values ('Pangwaun Township',11,false);
insert into city (name,state_id,del_flag) values ('Namtit Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Panlong Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Matman Township',11,false);
insert into city (name,state_id,del_flag) values ('Namphan Township',11,false);
insert into city (name,state_id,del_flag) values ('Pangsang Township',11,false);
insert into city (name,state_id,del_flag) values ('Man Kan Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Mabein Township',11,false);
insert into city (name,state_id,del_flag) values ('Mongmit Township',11,false);
insert into city (name,state_id,del_flag) values ('Langkho Township',11,false);
insert into city (name,state_id,del_flag) values ('Mawkmai Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong Nai Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong Pan Township',11,false);
insert into city (name,state_id,del_flag) values ('Homane Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Kengtaung Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Kunhing Township',11,false);
insert into city (name,state_id,del_flag) values ('Kyethi Township',11,false);
insert into city (name,state_id,del_flag) values ('Lai-Hka Township',11,false);
insert into city (name,state_id,del_flag) values ('Loilen Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong Hsu Township',11,false);
insert into city (name,state_id,del_flag) values ('Mong Kung Township',11,false);
insert into city (name,state_id,del_flag) values ('Nansang Township',11,false);
insert into city (name,state_id,del_flag) values ('Karli Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Kholan Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Minenaung Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Minesan Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Panglong Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Hopong Township',11,false);
insert into city (name,state_id,del_flag) values ('Hsi Hseng Township',11,false);
insert into city (name,state_id,del_flag) values ('Kalaw Township',11,false);
insert into city (name,state_id,del_flag) values ('Lawksawk Township',11,false);
insert into city (name,state_id,del_flag) values ('Nyaungshwe Township',11,false);
insert into city (name,state_id,del_flag) values ('Pekon Township',11,false);
insert into city (name,state_id,del_flag) values ('Pingdaya Township',11,false);
insert into city (name,state_id,del_flag) values ('Pinlaung Township',11,false);
insert into city (name,state_id,del_flag) values ('Taunggyi Township',11,false);
insert into city (name,state_id,del_flag) values ('Ywangan Township',11,false);
insert into city (name,state_id,del_flag) values ('Indaw Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Kyauktalongyi Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Naungtayar Subtownship',11,false);
insert into city (name,state_id,del_flag) values ('Hinthada Township',1,false);
insert into city (name,state_id,del_flag) values ('Lemyethna Township',1,false);
insert into city (name,state_id,del_flag) values ('Zalun Township',1,false);
insert into city (name,state_id,del_flag) values ('Ingapu Township',1,false);
insert into city (name,state_id,del_flag) values ('Kyangin Township',1,false);
insert into city (name,state_id,del_flag) values ('Myanaung Township',1,false);
insert into city (name,state_id,del_flag) values ('Labutta Township',1,false);
insert into city (name,state_id,del_flag) values ('Mawlamyinegyun Township',1,false);
insert into city (name,state_id,del_flag) values ('Pyinsalu Subtownship',1,false);
insert into city (name,state_id,del_flag) values ('Danuphyu Township',1,false);
insert into city (name,state_id,del_flag) values ('Ma-ubin Township',1,false);
insert into city (name,state_id,del_flag) values ('Nyaungdon Township',1,false);
insert into city (name,state_id,del_flag) values ('Pantanaw Township',1,false);
insert into city (name,state_id,del_flag) values ('Einme Township',1,false);
insert into city (name,state_id,del_flag) values ('Myaungmya Township',1,false);
insert into city (name,state_id,del_flag) values ('Wakema Township',1,false);
insert into city (name,state_id,del_flag) values ('Kangyidaunk Township',1,false);
insert into city (name,state_id,del_flag) values ('Ngapudaw Township',1,false);
insert into city (name,state_id,del_flag) values ('Pathein Township',1,false);
insert into city (name,state_id,del_flag) values ('Thabaung Township',1,false);
insert into city (name,state_id,del_flag) values ('Kyaunggon Township',1,false);
insert into city (name,state_id,del_flag) values ('Kyonpyaw Township',1,false);
insert into city (name,state_id,del_flag) values ('Yekyi Township',1,false);
insert into city (name,state_id,del_flag) values ('Ngayokaung Subtownship',1,false);
insert into city (name,state_id,del_flag) values ('Hainggyikyun Subtownship',1,false);
insert into city (name,state_id,del_flag) values ('Shwethaungyan Subtownship',1,false);
insert into city (name,state_id,del_flag) values ('Ngwehsaung Subtownship',1,false);
insert into city (name,state_id,del_flag) values ('Ngathaingchaung Subtownship',1,false);
insert into city (name,state_id,del_flag) values ('Bogale Township',1,false);
insert into city (name,state_id,del_flag) values ('Dedaye Township',1,false);
insert into city (name,state_id,del_flag) values ('Kyaiklat Township',1,false);
insert into city (name,state_id,del_flag) values ('Pyapon Township',1,false);
insert into city (name,state_id,del_flag) values ('Bago Township',2,false);
insert into city (name,state_id,del_flag) values ('Daik-U Township',2,false);
insert into city (name,state_id,del_flag) values ('Kawa Township',2,false);
insert into city (name,state_id,del_flag) values ('Nyaunglebin Township',2,false);
insert into city (name,state_id,del_flag) values ('Shwegyin Township',2,false);
insert into city (name,state_id,del_flag) values ('Thanatpin Township',2,false);
insert into city (name,state_id,del_flag) values ('Waw Township',2,false);
insert into city (name,state_id,del_flag) values ('Kyauktaga Township',2,false);
insert into city (name,state_id,del_flag) values ('Kyaukkyi Township',2,false);
insert into city (name,state_id,del_flag) values ('Oktwin Township',2,false);
insert into city (name,state_id,del_flag) values ('Pyu Township',2,false);
insert into city (name,state_id,del_flag) values ('Tantabin Township',2,false);
insert into city (name,state_id,del_flag) values ('Taungoo Township',2,false);
insert into city (name,state_id,del_flag) values ('Yedashe Township',2,false);
insert into city (name,state_id,del_flag) values ('Padaung Township',2,false);
insert into city (name,state_id,del_flag) values ('Paukkaung Township',2,false);
insert into city (name,state_id,del_flag) values ('Paungde Township',2,false);
insert into city (name,state_id,del_flag) values ('Pyay Township',2,false);
insert into city (name,state_id,del_flag) values ('Shwedaung Township',2,false);
insert into city (name,state_id,del_flag) values ('Thegon Township',2,false);
insert into city (name,state_id,del_flag) values ('Gyobingauk Township',2,false);
insert into city (name,state_id,del_flag) values ('Letpadan Township',2,false);
insert into city (name,state_id,del_flag) values ('Minhla Township',2,false);
insert into city (name,state_id,del_flag) values ('Monyo Township',2,false);
insert into city (name,state_id,del_flag) values ('Okpho Township',2,false);
insert into city (name,state_id,del_flag) values ('Tharrawaddy Township',2,false);
insert into city (name,state_id,del_flag) values ('Nattalin Township',2,false);
insert into city (name,state_id,del_flag) values ('Zigon Township',2,false);
insert into city (name,state_id,del_flag) values ('Botataung Township',14,false);
insert into city (name,state_id,del_flag) values ('Dagon Seikkan Township',14,false);
insert into city (name,state_id,del_flag) values ('East Dagon Township',14,false);
insert into city (name,state_id,del_flag) values ('North Dagon Township',14,false);
insert into city (name,state_id,del_flag) values ('North Okkalapa Township',14,false);
insert into city (name,state_id,del_flag) values ('Pazundaung Township',14,false);
insert into city (name,state_id,del_flag) values ('South Dagon Township',14,false);
insert into city (name,state_id,del_flag) values ('South Okkalapa Township',14,false);
insert into city (name,state_id,del_flag) values ('Thingangyun Township',14,false);
insert into city (name,state_id,del_flag) values ('Dawbon Township',14,false);
insert into city (name,state_id,del_flag) values ('Mingala Taungnyunt Township',14,false);
insert into city (name,state_id,del_flag) values ('Tamwe Township',14,false);
insert into city (name,state_id,del_flag) values ('Thaketa Township',14,false);
insert into city (name,state_id,del_flag) values ('Yankin Township',14,false);
insert into city (name,state_id,del_flag) values ('Hlaingthaya Township',14,false);
insert into city (name,state_id,del_flag) values ('Insein Township',14,false);
insert into city (name,state_id,del_flag) values ('Mingaladon Township',14,false);
insert into city (name,state_id,del_flag) values ('Shwepyitha Township',14,false);
insert into city (name,state_id,del_flag) values ('Hlegu Township',14,false);
insert into city (name,state_id,del_flag) values ('Hmawbi Township',14,false);
insert into city (name,state_id,del_flag) values ('Htantabin Township',14,false);
insert into city (name,state_id,del_flag) values ('Taikkyi Township',14,false);
insert into city (name,state_id,del_flag) values ('Dala Township',14,false);
insert into city (name,state_id,del_flag) values ('Seikkyi Kanaungto Township',14,false);
insert into city (name,state_id,del_flag) values ('Cocokyun Township',14,false);
insert into city (name,state_id,del_flag) values ('Kawhmu Township',14,false);
insert into city (name,state_id,del_flag) values ('Kayan Township',14,false);
insert into city (name,state_id,del_flag) values ('Kungyangon Township',14,false);
insert into city (name,state_id,del_flag) values ('Kyauktan Township',14,false);
insert into city (name,state_id,del_flag) values ('Thanlyin Township',14,false);
insert into city (name,state_id,del_flag) values ('Thongwa Township',14,false);
insert into city (name,state_id,del_flag) values ('Twante Township',14,false);
insert into city (name,state_id,del_flag) values ('Tada Subtownship',14,false);
insert into city (name,state_id,del_flag) values ('Ahlon Township',14,false);
insert into city (name,state_id,del_flag) values ('Bahan Township',14,false);
insert into city (name,state_id,del_flag) values ('Dagon Township',14,false);
insert into city (name,state_id,del_flag) values ('Kyauktada Township',14,false);
insert into city (name,state_id,del_flag) values ('Kyimyindaing Township',14,false);
insert into city (name,state_id,del_flag) values ('Lanmadaw Township',14,false);
insert into city (name,state_id,del_flag) values ('Latha Township',14,false);
insert into city (name,state_id,del_flag) values ('Pabedan Township',14,false);
insert into city (name,state_id,del_flag) values ('Sanchaung Township',14,false);
insert into city (name,state_id,del_flag) values ('Seikkan Township',14,false);
insert into city (name,state_id,del_flag) values ('Hlaing Township',14,false);
insert into city (name,state_id,del_flag) values ('Kamayut Township',14,false);
insert into city (name,state_id,del_flag) values ('Mayangon Township',14,false);
insert into city (name,state_id,del_flag) values ('Bhamo Township',4,false);
insert into city (name,state_id,del_flag) values ('Mansi Township',4,false);
insert into city (name,state_id,del_flag) values ('Momauk Township',4,false);
insert into city (name,state_id,del_flag) values ('Shwegu Township',4,false);
insert into city (name,state_id,del_flag) values ('Dotphoneyan Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Lwegel Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Myohla Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Hpakant Township',4,false);
insert into city (name,state_id,del_flag) values ('Mogaung Township',4,false);
insert into city (name,state_id,del_flag) values ('Mohnyin Township',4,false);
insert into city (name,state_id,del_flag) values ('Hopin Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Kamine Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Chipwi Township',4,false);
insert into city (name,state_id,del_flag) values ('Hsawlaw Township',4,false);
insert into city (name,state_id,del_flag) values ('Injangyang Township',4,false);
insert into city (name,state_id,del_flag) values ('Myitkyina Township',4,false);
insert into city (name,state_id,del_flag) values ('Tanai Township',4,false);
insert into city (name,state_id,del_flag) values ('Waingmaw Township',4,false);
insert into city (name,state_id,del_flag) values ('Hsadone Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Hsinbo Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Kanpaikti Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Panwa Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Shinbwayyan Subtownship',4,false);
insert into city (name,state_id,del_flag) values ('Kawnglanghpu Township',4,false);
insert into city (name,state_id,del_flag) values ('Machanbaw Township',4,false);
insert into city (name,state_id,del_flag) values ('Nogmung Township',4,false);
insert into city (name,state_id,del_flag) values ('Putao Township',4,false);
insert into city (name,state_id,del_flag) values ('Sumprabum Township',4,false);
insert into city (name,state_id,del_flag) values ('Hkamti Township',12,false);
insert into city (name,state_id,del_flag) values ('Homalin Township',12,false);
insert into city (name,state_id,del_flag) values ('Lahe Township',12,false);
insert into city (name,state_id,del_flag) values ('Leshi Township',12,false);
insert into city (name,state_id,del_flag) values ('Nanyun Township',12,false);
insert into city (name,state_id,del_flag) values ('Donhee Subtownship',12,false);
insert into city (name,state_id,del_flag) values ('Htanparkway Subtownship',12,false);
insert into city (name,state_id,del_flag) values ('Mobaingluk Subtownship',12,false);
insert into city (name,state_id,del_flag) values ('Pansaung Subtownship',12,false);
insert into city (name,state_id,del_flag) values ('Sonemara Subtownship',12,false);
insert into city (name,state_id,del_flag) values ('Kanbalu Township',12,false);
insert into city (name,state_id,del_flag) values ('Kyunhla Township',12,false);
insert into city (name,state_id,del_flag) values ('Taze Township',12,false);
insert into city (name,state_id,del_flag) values ('Ye-U Township',12,false);
insert into city (name,state_id,del_flag) values ('Kale Township',12,false);
insert into city (name,state_id,del_flag) values ('Kalewa Township',12,false);
insert into city (name,state_id,del_flag) values ('Mingin Township',12,false);
insert into city (name,state_id,del_flag) values ('Banmauk Township',12,false);
insert into city (name,state_id,del_flag) values ('Indaw Township',12,false);
insert into city (name,state_id,del_flag) values ('Katha Township',12,false);
insert into city (name,state_id,del_flag) values ('Kawlin Township',12,false);
insert into city (name,state_id,del_flag) values ('Pinlebu Township',12,false);
insert into city (name,state_id,del_flag) values ('Tigyaing Township',12,false);
insert into city (name,state_id,del_flag) values ('Wuntho Township',12,false);
insert into city (name,state_id,del_flag) values ('Mawlaik Township',12,false);
insert into city (name,state_id,del_flag) values ('Paungbyin Township',12,false);
insert into city (name,state_id,del_flag) values ('Ayadaw Township',12,false);
insert into city (name,state_id,del_flag) values ('Budalin Township',12,false);
insert into city (name,state_id,del_flag) values ('Chaung-U Township',12,false);
insert into city (name,state_id,del_flag) values ('Monywa Township',12,false);
insert into city (name,state_id,del_flag) values ('Myaung Township',12,false);
insert into city (name,state_id,del_flag) values ('Myinmu Township',12,false);
insert into city (name,state_id,del_flag) values ('Sagaing Township',12,false);
insert into city (name,state_id,del_flag) values ('Khin-U Township',12,false);
insert into city (name,state_id,del_flag) values ('Shwebo Township',12,false);
insert into city (name,state_id,del_flag) values ('Wetlet Township',12,false);
insert into city (name,state_id,del_flag) values ('Tabayin Township',12,false);
insert into city (name,state_id,del_flag) values ('Kyaukmyaung Subtownship',12,false);
insert into city (name,state_id,del_flag) values ('Tamu Township',12,false);
insert into city (name,state_id,del_flag) values ('Khampat Subtownship',12,false);
insert into city (name,state_id,del_flag) values ('Myothit Subtownship',12,false);
insert into city (name,state_id,del_flag) values ('Kani Township',12,false);
insert into city (name,state_id,del_flag) values ('Pale Township',12,false);
insert into city (name,state_id,del_flag) values ('Salingyi Township',12,false);
insert into city (name,state_id,del_flag) values ('Yinmabin Township',12,false);
insert into city (name,state_id,del_flag) values ('Chaungzon Township',9,false);
insert into city (name,state_id,del_flag) values ('Kyaikmaraw Township',9,false);
insert into city (name,state_id,del_flag) values ('Mawlamyine Township',9,false);
insert into city (name,state_id,del_flag) values ('Mudon Township',9,false);
insert into city (name,state_id,del_flag) values ('Thanbyuzayat Township',9,false);
insert into city (name,state_id,del_flag) values ('Ye Township',9,false);
insert into city (name,state_id,del_flag) values ('Khawzar Subtownship',9,false);
insert into city (name,state_id,del_flag) values ('Lamine Subtownship',9,false);
insert into city (name,state_id,del_flag) values ('Bilin Township',9,false);
insert into city (name,state_id,del_flag) values ('Kyaikto Township',9,false);
insert into city (name,state_id,del_flag) values ('Paung Township',9,false);
insert into city (name,state_id,del_flag) values ('Thaton Township',9,false);
insert into city (name,state_id,del_flag) values ('Dawei Township',13,false);
insert into city (name,state_id,del_flag) values ('Launglon Township',13,false);
insert into city (name,state_id,del_flag) values ('Thayetchaung Township',13,false);
insert into city (name,state_id,del_flag) values ('Yebyu Township',13,false);
insert into city (name,state_id,del_flag) values ('Kaleinaung Subtownship',13,false);
insert into city (name,state_id,del_flag) values ('Myitta Subtownship',13,false);
insert into city (name,state_id,del_flag) values ('Bokpyin Township',13,false);
insert into city (name,state_id,del_flag) values ('Kawthoung Township',13,false);
insert into city (name,state_id,del_flag) values ('Karathuri Subtownship',13,false);
insert into city (name,state_id,del_flag) values ('Khamaukgyi Subtownship',13,false);
insert into city (name,state_id,del_flag) values ('Pyigyimandaing Subtownship',13,false);
insert into city (name,state_id,del_flag) values ('Kyunsu Township',13,false);
insert into city (name,state_id,del_flag) values ('Myeik Township',13,false);
insert into city (name,state_id,del_flag) values ('Palaw Township',13,false);
insert into city (name,state_id,del_flag) values ('Tanintharyi Township',13,false);
insert into city (name,state_id,del_flag) values ('Palauk Subtownship',13,false);
insert into city (name,state_id,del_flag) values ('Falam Township',3,false);
insert into city (name,state_id,del_flag) values ('Tiddim Township',3,false);
insert into city (name,state_id,del_flag) values ('Ton Zang Township',3,false);
insert into city (name,state_id,del_flag) values ('Cikha Subtownship',3,false);
insert into city (name,state_id,del_flag) values ('Rikhuadal Subtownship',3,false);
insert into city (name,state_id,del_flag) values ('Hakha Township',3,false);
insert into city (name,state_id,del_flag) values ('Htantlang Township',3,false);
insert into city (name,state_id,del_flag) values ('Kanpetlet Township',3,false);
insert into city (name,state_id,del_flag) values ('Matupi Township',3,false);
insert into city (name,state_id,del_flag) values ('Mindat Township',3,false);
insert into city (name,state_id,del_flag) values ('Paletwa Township',3,false);
insert into city (name,state_id,del_flag) values ('Reazu Subtownship',3,false);
insert into city (name,state_id,del_flag) values ('Sami Subtownship',3,false);
insert into city (name,state_id,del_flag) values ('Ann Township',10,false);
insert into city (name,state_id,del_flag) values ('Kyaukpyu Township',10,false);
insert into city (name,state_id,del_flag) values ('Manaung Township',10,false);
insert into city (name,state_id,del_flag) values ('Ramree Township',10,false);
insert into city (name,state_id,del_flag) values ('Buthidaung Township',10,false);
insert into city (name,state_id,del_flag) values ('Maungdaw Township',10,false);
insert into city (name,state_id,del_flag) values ('Taungpyoletwe Subtownship',10,false);
insert into city (name,state_id,del_flag) values ('Pauktaw Township',10,false);
insert into city (name,state_id,del_flag) values ('Ponnagyun Township',10,false);
insert into city (name,state_id,del_flag) values ('Rathedaung Township',10,false);
insert into city (name,state_id,del_flag) values ('Sittwe Township',10,false);
insert into city (name,state_id,del_flag) values ('Gaw Township',10,false);
insert into city (name,state_id,del_flag) values ('Thandwe Township',10,false);
insert into city (name,state_id,del_flag) values ('Toungup Township',10,false);
insert into city (name,state_id,del_flag) values ('Kyeintali Subtownship',10,false);
insert into city (name,state_id,del_flag) values ('Maei Subtownship',10,false);
insert into city (name,state_id,del_flag) values ('Kyauktaw Township',10,false);
insert into city (name,state_id,del_flag) values ('Minbya Township',10,false);
insert into city (name,state_id,del_flag) values ('Mrauk-U Township',10,false);
insert into city (name,state_id,del_flag) values ('Myebon Township',10,false);
insert into itemstate (state,del_flag) values ('New',false);
insert into itemstate (state,del_flag) values ('Use',false);
insert into currency (name,code,symbol,isHomeCur,del_flag) values ('Kyat','001','MMK',false,false);
insert into category (name,del_flag) values ('Men',false);
insert into member (id,nickname,createuser,moduser) values(1,'Aung Aung',1,1);

insert into item (name,category_id,owner_id,createuser,moduser) values ('shirt',1,1,1,1);
insert into item (name,category_id,owner_id,createuser,moduser) values ('Pants',1,1,1,1);

insert into category (name,del_flag) values ('Woman',false);
insert into category (name,del_flag,parent_id) values ('Makeup',false,2);
insert into category (name,del_flag,parent_id) values ('Bag',false,2);
insert into category (name,del_flag,parent_id) values ('Lip Stick',false,3);
insert into category (name,del_flag,parent_id) values ('Skin Care',false,3);

insert into order_table (id,item_id,buyer_id,status,commissionrate,count,createuser,moduser,unitprice) values (1,1,1,'Pending',200.00,1,1,1,200.00);
insert into order_table (id,item_id,buyer_id,status,commissionrate,count,createuser,moduser,unitprice) values (2,1,1,'Processing',200.00,1,1,1,200.00);
insert into order_table (id,item_id,buyer_id,status,commissionrate,count,createuser,moduser,unitprice) values (3,1,1,'ConfirmShipment',200.00,1,1,1,200.00);
insert into order_table (id,item_id,buyer_id,status,commissionrate,count,createuser,moduser,unitprice) values (4,1,1,'Completed',200.00,1,1,1,200.00);
insert into order_table (id,item_id,buyer_id,status,commissionrate,count,createuser,moduser,unitprice) values (5,1,1,'Reject',200.00,1,1,1,200.00);
insert into order_table (id,item_id,buyer_id,status,commissionrate,count,createuser,moduser,unitprice) values (6,1,1,'Expired',200.00,1,1,1,200.00);




